### ISSUE TITLE
brew is reporting: Warning: Calling bottle :unneeded is deprecated! There is no replacement.

### ISSUE THREAD

**Issue by pgpx** [jzelinskie/homebrew-faq#1]
Hi, brew is now reporting (via `brew update` or `brew outdated`):

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the weaveworks/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/weaveworks/homebrew-tap/Formula/eksctl.rb:9
```

see https://github.com/Homebrew/brew/commit/f65d525693a45c8e4c2ebc1452080f08c363ee15#diff-f12455e8eb757e3223300c7c544b5b752394173c2a9bb0440443d5673b151fb3

**Comment by serdardalgic** [comment]
@jzelinskie just removing [this line](https://github.com/jzelinskie/homebrew-faq/blob/b68190fb532c756303b8e65d22cd7d021728c28c/Formula/faq.rb#L11) should fix the problem. 

I hit this problem when I install any package via homebrew:
```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the jzelinskie/faq tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/jzelinskie/homebrew-faq/Formula/faq.rb:11
```

**Comment by jzelinskie** [comment]
Thanks! I just fixed this in some other repos. I'll get to it later today.
